import { resolve } from 'path'
import * as path from 'path'
import { promises as fs } from 'fs'
import tailwindcss from '@tailwindcss/vite'
import { defineConfig, externalizeDepsPlugin, bytecodePlugin, type Plugin } from 'electron-vite'
import vue from '@vitejs/plugin-vue'
import tsconfigPaths from 'vite-tsconfig-paths'
import { readmePlugin } from './vite-plugin-readme'

// Preload-specific helper: remove the bytecode plugin when building the
// Preload-specific helper: remove any bytecode artifacts after the
// preload bundle is written, and rewrite the stub so it doesn't rely on
// `require`.  This lets us keep `sandbox: true` without having to
// disable the built-in bytecodePlugin (which is tricky to override).
function patchPreloadBytecode(): Plugin {
  let isPreload = false
  return {
    name: 'patch-preload-bytecode',
    apply: 'build',
    enforce: 'post',
    configResolved(resolvedConfig) {
      isPreload = resolvedConfig.plugins.some(
        (p) => p.name === 'vite:electron-preload-preset-config'
      )
    },
    async writeBundle(options, bundle) {
      if (!isPreload) return
      try {
        const outDir = (options.dir as string) || ''
        // only operate on the preload output directory
        if (!outDir.toLowerCase().endsWith('preload')) return
        const idxPath = path.resolve(outDir, 'index.js')
        let code = await fs.promises.readFile(idxPath, 'utf-8')
        // strip any require lines introduced by bytecodePlugin
        code = code
          .replace(/require\(['"]\.\/bytecode-loader\.cjs['"]\);?\s*/g, '')
          .replace(/require\(['"]\.\/index\.jsc['"]\);?\s*/g, '')
        await fs.promises.writeFile(idxPath, code, 'utf-8')
        // remove generated bytecode files if they exist
        for (const fname of ['bytecode-loader.cjs', 'index.jsc']) {
          const filePath = path.resolve(outDir, fname)
          try {
            await fs.promises.unlink(filePath)
          } catch {}
        }
      } catch (e) {
        // swallow errors; not critical
        console.warn('patchPreloadBytecode failed', e)
      }
    },
    generateBundle(_options, bundle) {      console.log('patchPreloadBytecode.generateBundle', { isPreload, keys: Object.keys(bundle) })      if (!isPreload) return
      for (const fileName of Object.keys(bundle)) {
        if (fileName === 'bytecode-loader.cjs' || fileName === 'index.jsc') {
          delete bundle[fileName]
          continue
        }
        if (fileName === 'index.js') {
          const chunk = bundle[fileName] as any
          if (chunk && typeof chunk.code === 'string') {
            chunk.code = chunk.code
              .replace(/require\(['"]\.\/bytecode-loader\.cjs['"]\);?\s*/g, '')
              .replace(/require\(['"]\.\/index\.jsc['"]\);?\s*/g, '')
          }
        }
      }
    }
  }
}

export default defineConfig({
  plugins: [patchPreloadBytecode()],
  main: {
    plugins: [
      externalizeDepsPlugin()
      // No PDFium WASM copying needed when using Chromium's built-in viewer
    ]
  },
  preload: {
    plugins: [
      externalizeDepsPlugin(),
      // bytecodePlugin is enabled by default in production; provide a
      // chunkAlias that will never match to effectively opt out for preload.
      bytecodePlugin({ chunkAlias: ['__disable__'] })
    ],
    // keeping default CommonJS output, sandboxed preload doesn't need ESM
    build: {
      target: 'es2022'
      // note: if you switch to format:'es' the bytecode plugin will warn and
      // still compile, so we leave it at the default (CJS) and simply disable
      // the plugin above.
    }
  },
  renderer: {
    resolve: {
      alias: {
        '@renderer': resolve('src/renderer/src'),
        '@': resolve(__dirname, './src/renderer/src')
      }
    },
    publicDir: resolve(__dirname, 'public'),
    plugins: [vue(), tailwindcss(), tsconfigPaths(), readmePlugin()]
  }
})
